// OFFICE DATA
export const CREATE_DATA_OFFICE = 'CREATE_DATA_OFFICE';
export const READ_ALL_DATA_OFFICE = 'READ_ALL_DATA_OFFICE';
export const UPDATE_DATA_OFFICE = 'UPDATE_DATA_OFFICE';
export const LOGIN_DATA_OFFICE = 'POST_DATA_OFFICE';
export const NO_DATA_OFFICE = 'NO_DATA_OFFICE';

//TOKEN

export const TOKEN = 'TOKEN';
export const NO_DATA_TOKEN = 'NO_DATA_TOKEN';


//USER DATA
export const USER_DATA = 'USER_DATA';
export const NO_DATA_USER = 'NO_DATA_USER';