import Head from "next/head";
import Image from "next/image";
import Footer from "../components/index/Footer";
import CardInfo from "../components/index/CardInfo";
import NavBar from "../components/index/NavBar";
import styles from "../styles/index.module.scss";
import {useState} from 'react';
import ModalHelper from '../components/index/ModalHelp';



export default function Index() {
  const [view, setView] = useState(false)
  const [open, setOpen] = useState(false);

  const handleMouse = (e) => {if (e)  setView(true)}
  const handleMouseOut = (e) => {if (e) setView(false)}
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  return (
    <div > 
      <Head>
        <title>Bienvenido a Arquitech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <div className={styles.container_vid}>
        <h1>
          LA MEJOR APP DE <span>REPORTES</span> PARA LOS PROYECTOS DE ARQUITECTURA
        </h1>
        <video className={styles.container} autoPlay muted loop>
          <source
            src="https://bucket-deveckor.s3.us-east-2.amazonaws.com/Fondo_arquitech.mp4"
            type="video/mp4"
          />
        </video>
      </div>
      <div className={styles.container_text}>
            <h1>Aplicación Projet Management de construcción</h1>
            <p>Arquitech es la aplicación para la mejor comunicación entre el constructor y el cliente, ahorrando tiempo, y costos.</p>
      </div>
      <div onMouseOver={handleMouse} onMouseOut={handleMouseOut}>

      <CardInfo
      key='i'
      view={view}
      />
      </div>
      <Footer
      handleOpen={handleOpen}
      open={open}
      />
      <ModalHelper
      handleClose={handleClose}
      open={open}
      />
    </div>

  );
}
